# Generated by Django 4.1 on 2022-09-26 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advertisement', '0006_alter_favorite_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, verbose_name='Имя пользователя')),
                ('description', models.TextField(verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('amount', models.PositiveIntegerField(verbose_name='Сумма с сомах')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачено')),
                ('advertisement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='advertisement.advertisement')),
            ],
            options={
                'verbose_name': 'Оплата',
                'verbose_name_plural': 'Оплаты',
            },
        ),
    ]
