# Generated by Django 4.1 on 2022-09-18 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='chat_id',
        ),
    ]
