# Generated by Django 4.1 on 2022-09-07 08:29

import cloudinary.models
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название товара')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('max_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена до')),
                ('description', models.TextField(max_length=4000, verbose_name='Ваше сообщение')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone_numbers', django.contrib.postgres.fields.ArrayField(base_field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефона'), size=8)),
                ('whatsapp_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='W/A номер')),
                ('type', models.CharField(choices=[('Активный', 'Активный'), ('На проверке', 'На проверке'), ('Неактивен', 'Неактивен')], default='На проверке', max_length=20, verbose_name='Статус объявления')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Последняя дата изменения')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Удален')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Категория')),
                ('icon', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('icon', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
        migrations.CreateModel(
            name='ViewStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views_count', models.PositiveIntegerField(verbose_name='Число просмотров')),
                ('contact_view_count', models.PositiveIntegerField(verbose_name='Статистика просмотров контактов')),
                ('date', models.DateField(auto_now=True, verbose_name='Дата')),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='advertisement.advertisement', verbose_name='Объявление')),
            ],
            options={
                'verbose_name': 'Статистика',
                'verbose_name_plural': 'Статистика',
            },
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='advertisement.advertisement', verbose_name='Объявление')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранные',
            },
        ),
        migrations.CreateModel(
            name='ChildCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Под-категория')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='child_categories', to='advertisement.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Под-категория',
                'verbose_name_plural': 'Под-категории',
            },
        ),
        migrations.AddField(
            model_name='advertisement',
            name='child_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='advertisement.childcategory', verbose_name='Подкатегория'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='advertisement.city'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.CreateModel(
            name='AdsSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(verbose_name='Дата окончания')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='advertisement.advertisement', verbose_name='Объявление')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='advertisement.subscription', verbose_name='Подписка')),
            ],
            options={
                'verbose_name': 'Подписка объявления',
                'verbose_name_plural': 'Подписки объявлений',
            },
        ),
        migrations.CreateModel(
            name='AdsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Фотография')),
                ('advertisement', models.ForeignKey(help_text='Объявления с фото получают в среднем в 3-5 раз больше откликов. Вы можете загрузить до 8 фотографий', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='advertisement.advertisement', verbose_name='Объявление')),
            ],
            options={
                'verbose_name': 'Изображение объявления',
                'verbose_name_plural': 'Изображения объявлений',
            },
        ),
        migrations.CreateModel(
            name='AdsComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Комментарий')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Последняя дата изменения')),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='advertisement.advertisement', verbose_name='Объявление')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='advertisement.adscomment', verbose_name='Родительский комментарий')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Коментарий',
                'verbose_name_plural': 'Кометарии',
                'ordering': ['created_on'],
            },
        ),
    ]
