# Generated by Django 4.1 on 2022-09-07 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advertisement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='favorites',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='childcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='child_categories', to='advertisement.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='child_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='advertisement.childcategory', verbose_name='Подкатегория'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='advertisement.city'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='adssubscriber',
            name='advertisement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='advertisement.advertisement', verbose_name='Объявление'),
        ),
        migrations.AddField(
            model_name='adssubscriber',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='advertisement.subscription', verbose_name='Подписка'),
        ),
        migrations.AddField(
            model_name='adsimage',
            name='advertisement',
            field=models.ForeignKey(help_text='Объявления с фото получают в среднем в 3-5 раз больше откликов. Вы можете загрузить до 8 фотографий', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='advertisement.advertisement', verbose_name='Объявление'),
        ),
        migrations.AddField(
            model_name='adscomment',
            name='advertisement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='advertisement.advertisement', verbose_name='Объявление'),
        ),
        migrations.AddField(
            model_name='adscomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='advertisement.adscomment', verbose_name='Родительский комментарий'),
        ),
        migrations.AddField(
            model_name='adscomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
