# Generated by Django 4.1 on 2022-08-23 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='max_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена до'),
        ),
    ]
