# Generated by Django 4.1 on 2022-09-20 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adsimage',
            options={'ordering': ['id'], 'verbose_name': 'Изображение объявления', 'verbose_name_plural': 'Изображения объявлений'},
        ),
        migrations.AlterModelOptions(
            name='adssubscriber',
            options={'ordering': ['id'], 'verbose_name': 'Подписка объявления', 'verbose_name_plural': 'Подписки объявлений'},
        ),
        migrations.AlterModelOptions(
            name='advertisement',
            options={'ordering': ['id'], 'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
        migrations.AlterModelOptions(
            name='complainingforads',
            options={'ordering': ['id'], 'verbose_name': 'Жалоба', 'verbose_name_plural': 'Жалобы'},
        ),
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ['id'], 'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранные'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['id'], 'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='advertisements',
        ),
        migrations.AddField(
            model_name='favorite',
            name='advertisements',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='advertisement.advertisement', verbose_name='Объявление'),
            preserve_default=False,
        ),
    ]
