# Generated by Django 4.1 on 2022-09-11 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ViewStatistic',
        ),
    ]
