# Generated by Django 4.1 on 2022-09-02 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=100, verbose_name='Название товара'), max_length=255),
        ),
    ]
