# Generated by Django 4.1 on 2022-08-23 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0002_alter_advertisement_max_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdsSubscribers',
            new_name='AdsSubscriber',
        ),
        migrations.RenameModel(
            old_name='Cities',
            new_name='City',
        ),
        migrations.RenameModel(
            old_name='ViewStatistics',
            new_name='ViewStatistic',
        ),
    ]
