# Generated by Django 4.1 on 2022-09-02 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0003_advertisement_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
