# Generated by Django 4.1 on 2022-09-11 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advertisement', '0003_delete_viewstatistic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adssubscriber',
            name='advertisement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='advertisement.advertisement', verbose_name='Объявление'),
        ),
        migrations.AlterField(
            model_name='adssubscriber',
            name='subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='advertisement.subscription', verbose_name='Подписка'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='child_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='advertisement.childcategory', verbose_name='Подкатегория'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='advertisement.city'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='type',
            field=models.CharField(choices=[('Активный', 'Активный'), ('На проверке', 'На проверке'), ('Неактивный', 'Неактивный')], default='На проверке', max_length=20, verbose_name='Статус объявления'),
        ),
        migrations.AlterField(
            model_name='childcategory',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_categories', to='advertisement.category', verbose_name='Категория'),
        ),
    ]
