# Generated by Django 4.1 on 2022-09-21 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0004_rename_advertisements_favorite_advertisement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complainingforads',
            name='advertisement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complain', to='advertisement.advertisement'),
        ),
    ]
