# Generated by Django 4.1 on 2022-09-12 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advertisement', '0004_alter_adssubscriber_advertisement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adssubscriber',
            name='advertisement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='advertisement.advertisement', verbose_name='Объявление'),
        ),
        migrations.AlterField(
            model_name='adssubscriber',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='advertisement.subscription', verbose_name='Подписка'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='child_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='advertisement.childcategory', verbose_name='Подкатегория'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='advertisement.city'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='childcategory',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_categories', to='advertisement.category', verbose_name='Категория'),
        ),
    ]
