# Generated by Django 4.1 on 2022-08-25 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0004_alter_city_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='favourites',
        ),
    ]
