# Generated by Django 4.1 on 2022-09-02 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0004_alter_advertisement_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='type',
            field=models.CharField(choices=[('Активный', 'Active'), ('На проверке', 'Checking'), ('Неактивен', 'Disable')], default='На проверке', max_length=20, verbose_name='Статус объявления'),
        ),
    ]
