# Generated by Django 4.1 on 2022-09-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0005_alter_advertisement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
