# Generated by Django 4.1 on 2022-09-12 07:35

import django.contrib.postgres.fields
from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0005_alter_adssubscriber_advertisement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='phone_numbers',
            field=django.contrib.postgres.fields.ArrayField(base_field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефона'), blank=True, null=True, size=8),
        ),
    ]
