# Generated by Django 4.1 on 2022-09-02 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0006_alter_advertisement_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='advertisement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', related_query_name='phone_number_queery', to='advertisement.advertisement', verbose_name='Объявление'),
        ),
    ]
