# Generated by Django 4.1 on 2022-09-14 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0006_alter_advertisement_phone_numbers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplainingForAds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Неверная рубрика', 'Неверная рубрика'), ('Запрещенный товар/услуга', 'Запрещенный товар/услуга'), ('Объявление не актуально', 'Объявление не актуально'), ('Неверный адрес', 'Неверный адрес'), ('Другое', 'Другое')], default='Неверная рубрика', max_length=100, verbose_name='Тип жалобы')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('advertisement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='advertisement.advertisement')),
            ],
            options={
                'verbose_name': 'Жалоба',
                'verbose_name_plural': 'Жалобы',
            },
        ),
    ]
