# Generated by Django 4.1 on 2022-09-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0007_complainingforads'),
    ]

    operations = [
        migrations.AddField(
            model_name='complainingforads',
            name='checked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата проверки'),
        ),
        migrations.AddField(
            model_name='complainingforads',
            name='is_checked',
            field=models.BooleanField(default=False, verbose_name='Проверен'),
        ),
        migrations.AddField(
            model_name='complainingforads',
            name='send_date',
            field=models.DateTimeField(auto_now_add=True, default='2022-06-13', verbose_name='Дата отправки'),
            preserve_default=False,
        ),
    ]
