# Generated by Django 4.1 on 2022-08-26 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0007_advertisement_is_delete'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('icon', models.ImageField(upload_to='', verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
        migrations.AlterModelOptions(
            name='adsimage',
            options={'verbose_name': 'Изображение объявления', 'verbose_name_plural': 'Изображения объявлений'},
        ),
        migrations.AlterModelOptions(
            name='adssubscriber',
            options={'verbose_name': 'Подписка объявления', 'verbose_name_plural': 'Подписки объявлений'},
        ),
        migrations.AlterModelOptions(
            name='advertisement',
            options={'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='childcategory',
            options={'verbose_name': 'Под-категория', 'verbose_name_plural': 'Под-категории'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
        migrations.AlterModelOptions(
            name='number',
            options={'verbose_name': 'Номер', 'verbose_name_plural': 'Номера'},
        ),
        migrations.AlterModelOptions(
            name='viewstatistic',
            options={'verbose_name': 'Статистика', 'verbose_name_plural': 'Статистика'},
        ),
        migrations.RemoveField(
            model_name='adssubscriber',
            name='type',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='head_image',
            field=models.ImageField(default=1, upload_to='', verbose_name='Главное изображение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adsimage',
            name='advertisement',
            field=models.ForeignKey(help_text='Объявления с фото получают в среднем в 3-5 раз больше откликов. Вы можете загрузить до 8 фотографий', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='advertisement.advertisement', verbose_name='Фотографии'),
        ),
        migrations.AddField(
            model_name='adssubscriber',
            name='subscription',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='advertisement.subscription', verbose_name='Подписка'),
            preserve_default=False,
        ),
    ]
