# Generated by Django 4.1 on 2022-08-28 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0008_subscription_alter_adsimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='child_category', to='advertisement.category', verbose_name='Категория'),
        ),
    ]
