# Generated by Django 4.1 on 2022-09-06 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0009_alter_advertisement_modified_at_adscomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adscomment',
            name='is_checked',
        ),
        migrations.AddField(
            model_name='adscomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='advertisement.adscomment', verbose_name='Родительский комментарий'),
        ),
    ]
