# Generated by Django 4.1 on 2022-09-18 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0010_alter_adssubscriber_advertisement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adscomment',
            options={'ordering': ['created_on'], 'verbose_name': 'Коментарий', 'verbose_name_plural': 'Коментарии'},
        ),
    ]
