# Generated by Django 4.1 on 2022-09-06 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0010_remove_adscomment_is_checked_adscomment_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adscomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='advertisement.adscomment', verbose_name='Родительский комментарий'),
        ),
        migrations.AlterField(
            model_name='adsimage',
            name='advertisement',
            field=models.ForeignKey(help_text='Объявления с фото получают в среднем в 3-5 раз больше откликов. Вы можете загрузить до 8 фотографий', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='advertisement.advertisement', verbose_name='Объявление'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='type',
            field=models.CharField(choices=[('Активный', 'Активный'), ('На проверке', 'На проверке'), ('Неактивен', 'Неактивен')], default='На проверке', max_length=20, verbose_name='Статус объявления'),
        ),
    ]
