# Generated by Django 4.1 on 2022-08-30 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0011_advertisement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='child_categories', to='advertisement.category', verbose_name='Категория'),
        ),
    ]
