# Generated by Django 4.1 on 2022-09-19 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0012_alter_favorite_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='advertisement',
        ),
        migrations.AddField(
            model_name='favorite',
            name='advertisement',
            field=models.ManyToManyField(related_name='favorites', to='advertisement.advertisement', verbose_name='Объявление'),
        ),
    ]
