# Generated by Django 4.1 on 2022-09-19 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0013_remove_favorite_advertisement_favorite_advertisement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='advertisement',
            new_name='advertisements',
        ),
    ]
