# Generated by Django 4.1 on 2022-09-13 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_activation_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='social_auth',
            field=models.CharField(blank=True, choices=[('google', 'google'), ('facebook', 'facebook')], max_length=20, null=True, verbose_name='Авторизован через: '),
        ),
    ]
