# Generated by Django 4.1 on 2022-09-14 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_social_auth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='social_auth',
        ),
    ]
