# Generated by Django 4.1 on 2022-08-24 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_groups_user_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='permission',
        ),
    ]
