# Generated by Django 4.1 on 2022-08-25 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0005_remove_advertisement_favourites'),
        ('user', '0007_remove_user_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favourites',
            field=models.ManyToManyField(blank=True, related_name='favourites', to='advertisement.advertisement', verbose_name='Избранные'),
        ),
    ]
