# Generated by Django 4.1 on 2022-08-30 01:07

from django.db import migrations
import user.manager


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_user_options_user_groups_user_user_permissions'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', user.manager.UserManager()),
            ],
        ),
    ]
