# Generated by Django 4.1 on 2022-09-11 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='copyright',
            field=models.CharField(max_length=100, verbose_name='Авторские права'),
        ),
    ]
