# Generated by Django 4.1 on 2022-09-07 04:49

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='logo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
