# Generated by Django 4.1 on 2022-08-24 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='subject',
            field=models.CharField(choices=[('BH', 'Помощь при покупке'), ('SB', 'Спонсорство'), ('ER', 'Ошибка')], default='ER', max_length=3, verbose_name='Тема сообщения'),
        ),
    ]
