# Generated by Django 4.1 on 2022-09-06 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='subject',
            field=models.CharField(choices=[('Помощь при покупке', 'Помощь при покупке'), ('Спонсорство', 'Спонсорство'), ('Ошибка', 'Ошибка')], default='Помощь при покупке', max_length=20, verbose_name='Тема сообщения'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='type',
            field=models.CharField(choices=[('Social Networks', 'Social Networks'), ('App', 'App')], default='Social Networks', max_length=20, verbose_name='Тип'),
        ),
    ]
