# Generated by Django 4.1 on 2022-09-19 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='feed_back_text',
            field=models.TextField(default=1, verbose_name='Связаться с администрацией, текст'),
            preserve_default=False,
        ),
    ]
