# Generated by Django 4.1 on 2022-09-12 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0002_alter_site_copyright'),
    ]

    operations = [
        migrations.AlterField(
            model_name='help',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='help', to='siteapp.helpcategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='siteapp.site', verbose_name='Сайт'),
        ),
    ]
