# Generated by Django 4.1 on 2022-09-06 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0002_alter_feedback_subject_alter_socialmedia_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.AlterField(
            model_name='feedback',
            name='subject',
            field=models.CharField(choices=[('Жалоба', 'Жалоба'), ('Предложение', 'Предложение')], default='Жалоба', max_length=20, verbose_name='Тема сообщения'),
        ),
        migrations.AddField(
            model_name='help',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='help', to='siteapp.helpcategory', verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
