# Generated by Django 4.1 on 2022-08-25 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0003_alter_feedback_options_alter_help_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='subject',
            field=models.CharField(choices=[('BH', 'Помощь при покупке'), ('SB', 'Спонсорство'), ('ER', 'Ошибка')], default='BH', max_length=3, verbose_name='Тема сообщения'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='type',
            field=models.CharField(choices=[('SN', 'Social Networks'), ('App', 'App')], default='SN', max_length=3, verbose_name='Тип'),
        ),
    ]
