# Generated by Django 4.1 on 2022-09-16 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0004_alter_help_category_alter_socialmedia_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='subject',
            field=models.CharField(choices=[('жалоба', 'жалоба'), ('предложение', 'предложение')], default='жалоба', max_length=20, verbose_name='Тема сообщения'),
        ),
    ]
